language: node_js

cache:
  directories:
    - ./client-server/node_modules

node_js:
  - "7"

branches:
  only:
    - /^feature\/step/

install:
  - cd ./client-server
  - npm install

script:
  - npm test
