language: node_js

cache:
  directories:
    - ./api-server/node_modules
    - ./client-server/node_modules

node_js:
  - "7"

branches:
  only:
    - /^feature\/step/

install:
  - sh npm_install api-server
  - sh npm_install client-server

script:
  - sh test api-server
  - sh test client-server
