version: '2'
services:
  api:
    build: ./api-server
    volumes:
      - ./api-server:/usr/src/api-server
      - /usr/src/api-server/node_modules
    ports:
      - "8080:8080"
  web:
    build: ./client-server
    volumes:
      - ./client-server:/usr/src/client-server
      - /usr/src/client-server/node_modules
    ports:
      - "3000:3000"
      - "9876:9876"
