export default {
  // action creator
  ON_INIT_LOADING_FINISHED: 'ON_INIT_LOADING_FINISHED',
  ON_CREATE_FORM_SUBMIT: 'ON_CREATE_FORM_SUBMIT',
  ON_MODAL_EDIT: 'ON_MODAL_EDIT',
  ON_ELEMENT_ITEM_DELETE: 'ON_ELEMENT_ITEM_DELETE',
  ON_ELEMENT_LIST_INIT: 'ON_ELEMENT_LIST_INIT:',

  // SAGA_STATE
  ELEMENT_LIST_FETCH_SUCCEEDED: 'ELEMENT_LIST_FETCH_SUCCEEDED',
  ON_CREATE_FORM_SUBMIT_SUCCEEDED: 'ON_CREATE_FORM_SUBMIT_SUCCEEDED',
  ON_MODAL_EDIT_SUCCEEDED: 'ON_MODAL_EDIT_SUCCEEDED',
  ON_ELEMENT_ITEM_DELETE_SUCCEEDED: 'ON_ELEMENT_ITEM_DELETE_SUCCEEDED',

  // option value of priority
  PRIORITY_DEFAULT: '',
  PRIORITY_EMERGENCY: 'Emergency',
  PRIORITY_IMPORTANT: 'Important',
  PRIORITY_NORAML: 'Normal',
  PRIORITY_NOTHING: 'Nothing',

  // option value of status
  STATUS_DEFAULT: '',
  STATUS_OPEN: 'Open',
  STATUS_PENDING: 'Pending',
  STATUS_PROCESSING: 'Processing',
  STATUS_CLOSED: 'Closed',

  // default value of other filed.
  OWNER_DEFAULT: '',
  TITLE_DEFAULT: '',
  CATEGORY_DEFAULT: '',

  // others
  COLUMN_TITLES: ['owner', 'title', 'category', 'status', 'priority'],
  HTTP_STATUS_200: 200,
};
